DROP TABLE IF EXISTS stats CASCADE;

CREATE TABLE IF NOT EXISTS stats(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(100),
    uri varchar(100),
    ip varchar(20),
    timestamp TIMESTAMP WITHOUT TIME ZONE
);